# Generated by Django 3.0.7 on 2020-06-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_bibliotecas_userdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroinstancias',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libroInstancia', to='gestionPedidos.Bibliotecas'),
        ),
    ]
